// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_group1_layout from "./routes/(group1)/_layout.tsx";
import * as $_group1_g1 from "./routes/(group1)/g1.tsx";
import * as $_group2_layout from "./routes/(group2)/_layout.tsx";
import * as $_group2_g2 from "./routes/(group2)/g2.tsx";
import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $about_layout from "./routes/about/_layout.tsx";
import * as $about_middleware from "./routes/about/_middleware.ts";
import * as $about_contact from "./routes/about/contact.tsx";
import * as $about_index from "./routes/about/index.tsx";
import * as $admin_layout from "./routes/admin/_layout.tsx";
import * as $admin_middleware from "./routes/admin/_middleware.ts";
import * as $admin_index from "./routes/admin/index.tsx";
import * as $admin_login from "./routes/admin/login.tsx";
import * as $admin_resume_edit from "./routes/admin/resume/edit.tsx";
import * as $admin_resume_index from "./routes/admin/resume/index.tsx";
import * as $admin_token from "./routes/admin/token.tsx";
import * as $admin_user from "./routes/admin/user.tsx";
import * as $api_joke from "./routes/api/joke.ts";
import * as $api_resume from "./routes/api/resume.ts";
import * as $api_test from "./routes/api/test.ts";
import * as $api_user_login from "./routes/api/user/login.ts";
import * as $async_page from "./routes/async-page.tsx";
import * as $definehelper from "./routes/definehelper.tsx";
import * as $greet_name_ from "./routes/greet/[name].tsx";
import * as $index from "./routes/index.tsx";
import * as $login from "./routes/login.tsx";
import * as $resume_index from "./routes/resume/index.tsx";
import * as $skipappwrapp from "./routes/skipappwrapp.tsx";
import * as $Counter from "./islands/Counter.tsx";
import * as $LoginForm from "./islands/LoginForm.tsx";
import * as $resume_edit from "./islands/resume/edit.tsx";
import * as $resume_resumetable from "./islands/resume/resumetable.tsx";
import * as $user_tokentable from "./islands/user/tokentable.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/(group1)/_layout.tsx": $_group1_layout,
    "./routes/(group1)/g1.tsx": $_group1_g1,
    "./routes/(group2)/_layout.tsx": $_group2_layout,
    "./routes/(group2)/g2.tsx": $_group2_g2,
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/about/_layout.tsx": $about_layout,
    "./routes/about/_middleware.ts": $about_middleware,
    "./routes/about/contact.tsx": $about_contact,
    "./routes/about/index.tsx": $about_index,
    "./routes/admin/_layout.tsx": $admin_layout,
    "./routes/admin/_middleware.ts": $admin_middleware,
    "./routes/admin/index.tsx": $admin_index,
    "./routes/admin/login.tsx": $admin_login,
    "./routes/admin/resume/edit.tsx": $admin_resume_edit,
    "./routes/admin/resume/index.tsx": $admin_resume_index,
    "./routes/admin/token.tsx": $admin_token,
    "./routes/admin/user.tsx": $admin_user,
    "./routes/api/joke.ts": $api_joke,
    "./routes/api/resume.ts": $api_resume,
    "./routes/api/test.ts": $api_test,
    "./routes/api/user/login.ts": $api_user_login,
    "./routes/async-page.tsx": $async_page,
    "./routes/definehelper.tsx": $definehelper,
    "./routes/greet/[name].tsx": $greet_name_,
    "./routes/index.tsx": $index,
    "./routes/login.tsx": $login,
    "./routes/resume/index.tsx": $resume_index,
    "./routes/skipappwrapp.tsx": $skipappwrapp,
  },
  islands: {
    "./islands/Counter.tsx": $Counter,
    "./islands/LoginForm.tsx": $LoginForm,
    "./islands/resume/edit.tsx": $resume_edit,
    "./islands/resume/resumetable.tsx": $resume_resumetable,
    "./islands/user/tokentable.tsx": $user_tokentable,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
